# Generated by Django 4.2 on 2023-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netflix', models.CharField(max_length=50)),
                ('kinopoisk', models.CharField(max_length=50)),
                ('ivi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socks_proxy', models.CharField(max_length=50)),
                ('ipv_four_proxy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='qiwi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiwi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_premium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='steam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_mmr_account', models.CharField(max_length=50)),
                ('medium_mmr_account', models.CharField(max_length=50)),
                ('high_mmr_account', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfshark', models.CharField(max_length=50)),
                ('expressVPN', models.CharField(max_length=50)),
                ('hideME', models.CharField(max_length=50)),
                ('protonPREMIUM', models.CharField(max_length=50)),
            ],
        ),
    ]
